"""Build Verba.app: a Dock-launchable wrapper around the console.

The bundle is a thin launcher. It finds a usable Python, pulls the staging
credentials out of the login keychain (prompting once and storing them if they
are not there yet), starts the console, and opens the browser. Quitting the app
stops the server, because the launcher runs it in the foreground.

Nothing about the pipeline lives in here: the app is a shortcut, not a fork.
"""
from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
APP_NAME = "Verba"

# What this app used to be called. A Dock tile keeps the label it was added
# under, so after a rename the refresh looked for "Verba", found a tile labelled
# "RiseDoc", decided the app was not in the Dock and did nothing. The tile then
# pointed at a bundle that had been deleted: clicking it did nothing at all, no
# bounce, no error, no log, because the launcher never ran.
PREVIOUS_NAMES = ("RiseDoc",)
BUNDLE_ID = "io.risecodes.verba"
KEYCHAIN_SERVICE = "verba-staging"
PORT = 8800

LAUNCHER = r'''#!/bin/bash
# Verba launcher. Generated by tools/build_app.py, edit that instead.
set -uo pipefail

PROJECT="__PROJECT__"
PORT=__PORT__
SERVICE="__SERVICE__"
URL="http://127.0.0.1:${PORT}"
LOG="$HOME/Library/Logs/Verba.log"
mkdir -p "$(dirname "$LOG")"

note()  { echo "$(date '+%H:%M:%S') $*" >> "$LOG"; }
# Visible feedback matters: without it a launch that succeeds instantly is
# indistinguishable from one that never happened.
toast() {
  /usr/bin/osascript -e "display notification \"$1\" with title \"Verba\"" \
    >/dev/null 2>&1 || true
}
show() { /usr/bin/open "$URL" >/dev/null 2>&1; }
alert() {
  note "ERROR: $*"
  /usr/bin/osascript -e "display alert \"Verba\" message \"$1\" as critical" >/dev/null 2>&1
}

note "--- launch ---"

# A login-shell PATH, so pyenv and homebrew resolve the way they do in Terminal.
if [ -f "$HOME/.zshrc" ]; then
  export PATH="$(/bin/zsh -lc 'echo $PATH' 2>/dev/null || echo "$PATH")"
fi

if [ ! -d "$PROJECT/verba" ]; then
  alert "The project folder was not found at $PROJECT."
  exit 1
fi
cd "$PROJECT" || { alert "Could not open $PROJECT."; exit 1; }

# Probe by importing what verba actually imports. A shallow `import PIL`
# succeeds even when Pillow's native extension is built for the wrong
# architecture, which then fails at render time instead of here.
PROBE='from PIL import Image; import docx, yaml, jinja2, playwright; import verba.drift, verba.render.docx'
PY=""
PY_WHY=""
for c in "$HOME/.pyenv/shims/python3" "$(command -v python3 || true)" \
         /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
  [ -n "$c" ] && [ -x "$c" ] || continue
  if OUT=$("$c" -c "$PROBE" 2>&1); then PY="$c"; break; fi
  note "rejected $c: $(echo "$OUT" | tail -1)"
  PY_WHY="$(echo "$OUT" | tail -1)"
done
if [ -z "$PY" ]; then
  alert "No usable Python was found. Last error: ${PY_WHY:-unknown}. In Terminal, run: python3 -m pip install python-docx pillow pyyaml jinja2 playwright anthropic"
  exit 1
fi
note "python: $PY"

# Already running? Bring the window up and stop. Checked before anything else so
# a second launch never asks for credentials it does not need.
if /usr/bin/curl -s -o /dev/null -m 2 "$URL/api/state"; then
  note "console already running, opening browser"
  toast "Already running. Opening the window."
  show
  exit 0
fi

# Credentials belong to connection profiles now (content/environments.yaml,
# keychain service verba-env-<id>), which the console manages. The launcher
# deliberately reads none: a second source of truth here produced a console that
# reported one signed-in user while crawling as another.

toast "Starting..."

# Poll until the console answers, then show it. Polling rather than a fixed
# sleep, so a slow first start still opens the window instead of silently
# leaving the user looking at nothing.
(
  for _ in $(seq 1 40); do
    if /usr/bin/curl -s -o /dev/null -m 2 "$URL/api/state"; then
      show
      toast "Ready."
      exit 0
    fi
    sleep 0.5
  done
  toast "The console did not start. See ~/Library/Logs/Verba.log"
) &

note "starting console on $PORT"
exec "$PY" -m verba console --port "$PORT" --no-open >> "$LOG" 2>&1
'''


def build(dest_dir: Path) -> Path:
    app = dest_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    res = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    res.mkdir(parents=True)

    icns = PROJECT / "tools" / "icon" / "Verba.icns"
    if not icns.exists():
        subprocess.run([sys.executable, str(PROJECT / "tools" / "make_icon.py")],
                       check=True, capture_output=True)
    shutil.copyfile(icns, res / f"{APP_NAME}.icns")

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": "Verba",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": APP_NAME,
        "CFBundleIconFile": f"{APP_NAME}.icns",
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.productivity",
        "NSHumanReadableCopyright": "Rise",
    }
    with open(app / "Contents" / "Info.plist", "wb") as fh:
        plistlib.dump(info, fh)

    launcher = macos / APP_NAME
    launcher.write_text(
        LAUNCHER.replace("__PROJECT__", str(PROJECT))
                .replace("__PORT__", str(PORT))
                .replace("__SERVICE__", KEYCHAIN_SERVICE),
        encoding="utf-8")
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    # Strip provenance/quarantine, which can make Gatekeeper refuse a locally
    # built bundle without ever showing a reason.
    subprocess.run(["xattr", "-cr", str(app)], capture_output=True)

    # Ad-hoc sign so the bundle has a stable identity.
    subprocess.run(["codesign", "--force", "--deep", "--sign", "-", str(app)],
                   capture_output=True)

    # Re-register with Launch Services: the bundle was just replaced, so the
    # old registration points at an inode that no longer exists.
    subprocess.run(
        ["/System/Library/Frameworks/CoreServices.framework/Frameworks/"
         "LaunchServices.framework/Support/lsregister", "-f", str(app)],
        capture_output=True)

    refresh_dock(app)
    return app


def refresh_dock(app: Path) -> str:
    """Rebuild the Dock entry if one exists.

    The Dock stores a bookmark to the bundle, not just its path. Replacing the
    bundle (which a rebuild does) leaves that bookmark pointing at an inode that
    is gone, and the icon then bounces once and gives up with nothing logged
    anywhere. Removing and re-adding the tile forces a fresh bookmark.
    """
    try:
        raw = subprocess.run(["defaults", "export", "com.apple.dock", "-"],
                             capture_output=True).stdout
        d = plistlib.loads(raw)
    except Exception:
        return "could not read the Dock"

    apps = d.get("persistent-apps", [])

    def label(tile):
        return (tile.get("tile-data", {}) or {}).get("file-label", "")

    def path_of(tile):
        url = ((tile.get("tile-data", {}) or {}).get("file-data", {}) or {})
        return str(url.get("_CFURLString", ""))

    wanted = (APP_NAME, *PREVIOUS_NAMES)
    index = next((i for i, tile in enumerate(apps) if label(tile) in wanted), None)
    if index is None:
        # Nothing by name. Adopt a tile pointing at a bundle that is gone, which
        # is what a rename leaves behind and is dead either way.
        index = next((i for i, tile in enumerate(apps)
                      if "verba" in path_of(tile).lower()
                      or "risedoc" in path_of(tile).lower()), None)
    if index is None:
        return "not in the Dock, nothing to refresh"
    was = label(apps[index])

    apps[index] = {
        "GUID": 0,
        "tile-data": {
            "file-data": {"_CFURLString": str(app), "_CFURLStringType": 0},
            "file-label": APP_NAME,
            "file-type": 41,
        },
        "tile-type": "file-tile",
    }
    d["persistent-apps"] = apps
    try:
        subprocess.run(["defaults", "import", "com.apple.dock", "-"],
                       input=plistlib.dumps(d), check=True)
        subprocess.run(["killall", "Dock"], capture_output=True)
        return ("Dock entry refreshed"
                if was == APP_NAME else
                f"Dock entry replaced: it still said {was!r} and pointed "
                f"at a bundle that no longer exists")
    except Exception as e:
        return f"could not refresh the Dock: {e}"


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Applications"
    target.mkdir(parents=True, exist_ok=True)
    built = build(target)
    print(built)
    print("the Dock entry was rebuilt, so its bookmark points at the new bundle")
